Yuri romanowski/#36 append inferred date parts
serokell/tzbot pull request #57
Opened 2023-02-02 18:24 UTC by YuriRomanowski

## Description

Problem: Full date is not shown for the original time reference, which
can be useful for receivers.
    
Solution: Append inferred parts of the date to the quoted original time
reference text.

## Related issue(s)

Fixed #36 

## :white_check_mark: Checklist for your Pull Request

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

#### Stylistic guide (mandatory)

- [ ] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [ ] My code complies with the [style guide](../tree/master/docs/code-style.md).

2023-02-09 17:22 UTC, dcastro commented on test/Test/TzBot/RenderSpec.hs
> +  ]
Please also add tests for these scenarios:

* Implicit date & explicit weekday: "10am on wednesday"
* Implicit date & explicit days from today: "10am in 3 days"
* Explicit day & implicit month: "10am on the 21st"

2023-02-12 14:35 UTC, dcastro approved these changes

2023-02-14 09:51 UTC, dcastro requested changes

2023-02-14 09:51 UTC, dcastro commented on src/TzBot/TimeReference.hs
> +            TZT.atTimeOfDay trTimeOfDay refDate
I see you replaced `modifyLocalStrict` with a couple of back-and-forth conversions (`tzTimeLocalTime` and then `fromLocalTimeStrict`).

I'm guessing you did that so you could grab the invalid date in line 131:

```hs
        Left err ->
          tzErrorToResult implicitSenderTimezone tzLabel (localDay refDate) err
```

However, the invalid date is already contained inside the `err` variable, so i think it's more appropriate to fetch it from `err` instead, and continue using `modifyLocalStrict` as before:

```diff
-  tzErrorToResult :: Bool -> TZLabel -> Day -> TZT.TZError -> TimeReferenceToUTCResult
-  tzErrorToResult implicitSenderTimezone tzLabel refDay = \case
-    TZT.TZOverlap {} -> TRTUAmbiguous $
-      TimeShiftErrorInfo implicitSenderTimezone tzLabel refDay
-    TZT.TZGap {}     -> TRTUInvalid $
-      TimeShiftErrorInfo implicitSenderTimezone tzLabel refDay
+  tzErrorToResult :: Bool -> TZLabel -> TZT.TZError -> TimeReferenceToUTCResult
+  tzErrorToResult implicitSenderTimezone tzLabel = \case
+    TZT.TZOverlap invalidLocalTime _ _ -> TRTUAmbiguous $
+      TimeShiftErrorInfo implicitSenderTimezone tzLabel (localDay invalidLocalTime)
+    TZT.TZGap invalidLocalTime _ _ -> TRTUInvalid $
+      TimeShiftErrorInfo implicitSenderTimezone tzLabel (localDay invalidLocalTime)
```

2023-02-14 09:54 UTC, dcastro commented on src/TzBot/TimeReference.hs
> +          eventTZTime = TZT.fromUTC (TZI.fromLabel tzLabel) eventTimestamp
The expression ` TZI.fromLabel tzLabel` is repeated twice in lines 124 and 125.

Not a big deal though, after applying the refactoring I mentioned in my other comment, the variable `tzInfo` will no longer be needed anyway.

2023-02-14 17:16 UTC, YuriRomanowski commented on src/TzBot/TimeReference.hs
> +            TZT.atTimeOfDay trTimeOfDay refDate
Yes, you are right :+1:

2023-02-15 08:14 UTC, dcastro approved these changes
LGTM! ;)

2023-02-16 14:23 UTC, merged